model: yolov5s-cls.pt
data: ../regurgitationV1_classify
epochs: 300
batch_size: 128
imgsz: 416
nosave: true
cache: ram
device: ''
workers: 8
project: runs/train-cls
name: classify
exist_ok: false
pretrained: true
optimizer: Adam
lr0: 0.001
decay: 5.0e-05
label_smoothing: 0.1
cutoff: null
dropout: null
verbose: false
seed: 0
local_rank: -1
save_dir: runs/train-cls/classify
